modLoader="javafml"
loaderVersion="[37,)"
license="AFL-3.0"
[[mods]]
modId="cheese_dragon"
version="${file.jarVersion}"
displayName="Cheese_Dragon"
logoFile="examplemod.png"
credits="Someoneice"
authors="Someoneice"
description='''
你无法再使用床来威胁末影龙！
'''
[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
